<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-UrlShortener.AnalyticsWorker-471a4c0d-c484-486f-a8b5-cc8d3d8632e0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UrlShortener.Application\UrlShortener.Application.csproj" />
    <ProjectReference Include="..\UrlShortener.Domain\UrlShortener.Domain.csproj" />
    <ProjectReference Include="..\UrlShortener.Infrastructure\UrlShortener.Infrastructure.csproj" />
  </ItemGroup>
</Project>
